##Consultar desde el gateway http://localhost:5224/ms-books-catalogue/api/v1/catalogue
server:
  port: ${PORT:5227}
  servlet:
    context-path: '/api/v1/catalogue'
spring:
  application:
    name: ms-books-catalogue
## Configuración CLiente Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:5225/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-books-catalogue
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
##Elasticsearch confi
elasticsearch:
  host: unir-search-1279391337.us-east-1.bonsaisearch.net
  credentials:
    user: 12gqcerxtl
    password: splvj99148
logging:
  level:
    tracer: TRACE